SET IDENTITY_INSERT SD_INFO ON;
INSERT SD_INFO (SD_ID,TC_PROJ_ID,TC_PROJ_TYPE,SD_CODE,SD_NAME,SD_ALIAS,ITEM_CAT_PA_CODE,CITEM_CAT_PA_CODE,EKPI_CAT_PA_CODE,ORDER_NO,VALID_FLAG,UPD_USER_ID,UPD_DATE) VALUES (1,10001,1,N'ACT',N'病种名称',N'别名',N'SD_ITEM_COMMON',NULL,NULL,1,1,N'zlt', CAST(N'2017/7/31 11:16:50' AS DateTime));
SET IDENTITY_INSERT SD_INFO OFF;
SET IDENTITY_INSERT SD_EKPI_INFO ON;
SET IDENTITY_INSERT SD_EKPI_INFO OFF;
